### ISSUE TITLE
Option to add more than 1 Spot editors

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#101]
Please do add the option to add more than 1 entry for the spot editor field.
![screen shot 2016-01-13 at 10 10 44 am](https://cloud.githubusercontent.com/assets/13643153/12303209/f1b47858-b9dd-11e5-94c8-63bdf6f937b3.png)

**Comment by kevinsiji** [comment]
ഡൺ.

![screencapture-www-m3db-com-node-add-film-1452749476473](https://cloud.githubusercontent.com/assets/3263439/12316599/84151434-baae-11e5-853e-088291eca117.png)
