### ISSUE TITLE
Song Recording - Studios not listing

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#102]
![screen shot 2016-01-14 at 11 01 05 am](https://cloud.githubusercontent.com/assets/13643153/12334311/3f321d30-baae-11e5-8b39-7fef71549ead.png)
![screen shot 2016-01-14 at 11 00 57 am](https://cloud.githubusercontent.com/assets/13643153/12334313/41ffc530-baae-11e5-9c13-73f6338f1d55.png)

**Comment by kevinsiji** [comment]
ഫിക്സ്ഡ്.

സുൻസയുടെ ഭാഷ ന്യൂട്രലായിരുന്നു. അതു ഞാൻ മലയാളമാക്കിയിട്ടുണ്ടു്. ഇപ്പോ വരും.

**Comment by Jayakrishnantu** [comment]
👍🏻

On Friday, January 15, 2016, kevinsiji notifications@github.com wrote:

> Closed #102 https://github.com/kevinsiji/m3db/issues/102.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kevinsiji/m3db/issues/102#event-516880010.

## 

_Best Regards,_
Jayakrisnan Unnikrishnapillai
Cell # 408 643 9782
