### ISSUE TITLE
തൽസമയ ശബ്ദലേഖനം

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#103]
Can we start displaying the 'തൽസമയ ശബ്ദലേഖനം' field on the film page?

**Comment by rakeshkonni** [comment]
We first identified the missing fields and first task was to order those
fields in the edit page. That's almost done. Front end restructuring is
created as a separate task. Kevin would be doing this soon

**Comment by kevinsiji** [comment]
> Can we start displaying the 'തൽസമയ ശബ്ദലേഖനം' field on the film page?

It is there on the film page. In the "Audio & Recording" section.

**Comment by Jayakrishnantu** [comment]
It wasn't showing. May be because of the Caching :-)

_Best Regards,_
Jayakrisnan Unnikrishnapillai
Cell # 408 643 9782
