### ISSUE TITLE
 സബ്ടൈറ്റിലിംഗ്

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#104]
Can we start displaying 'സബ്ടൈറ്റിലിംഗ്' field on Film pages?

**Comment by rakeshkonni** [comment]
Film Page rework is in progress. Or yet to start. This will be covered
there

**Comment by kevinsiji** [comment]
Subtitling is displayed under the section `Technical Crew`.

**Comment by Jayakrishnantu** [comment]
Actually, I meant it to be displayed on Artist page. :D

**Comment by rakeshkonni** [comment]
ഡിസ്പ്ലേ സൈഡ് വേറൊരു ഇഷ്യൂ  ആയി ഇട്ടിട്ടുണ്ട്. മൊത്തം ഫിലിം പേജിന്റെ
ഡിസ്പ്ലേ

Regards,
Rakesh
