### ISSUE TITLE
Recording Field is showing all artist's profile

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#105]
Somehow in all artist's profiles, same set of 'Recording' details are showing

Kollam Ajith
![screen shot 2016-01-19 at 12 53 13 pm](https://cloud.githubusercontent.com/assets/13643153/12431729/ed63df46-beab-11e5-97e2-ccd5a4012ed5.png)

Mammootty
![screen shot 2016-01-19 at 12 54 41 pm](https://cloud.githubusercontent.com/assets/13643153/12431730/efeaeb10-beab-11e5-8695-2b4a24dab583.png)

**Comment by kevinsiji** [comment]
Fixed.

**Comment by Jayakrishnantu** [comment]
👍🏻👍🏻👍🏻

On Tuesday, January 19, 2016, kevinsiji notifications@github.com wrote:

> Closed #105 https://github.com/kevinsiji/m3db/issues/105.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kevinsiji/m3db/issues/105#event-519945570.

## 

_Best Regards,_
Jayakrisnan Unnikrishnapillai
Cell # 408 643 9782
