### ISSUE TITLE
Language Neutral Nodes

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#107]
@kevinsiji 
Any options to list down all the Artists, Studio, Banner & other nodes which are language neutral ?They won't show up in the search and we ends up creating duplicates :(
If you can get us a list, we can manually change all of them. Can you build a list ?

**Comment by kevinsiji** [comment]
http://www.m3db.com/contentadmin
1. Goto this page. 
2. In the dropdown "Node translation: Language", select "No language".
3. Click Apply.
4. Check all those you want to change the language.
5. Click "Modify entity values".
6. In the next page, select the language and click Next.
7. Click Confirm.
