### ISSUE TITLE
Add Sub-titling to Artist Fields

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#114]
@kevinsiji 
Can you please add the sub-titling  also to the Artist field list drop down in the artist edit page?

**Comment by rakeshkonni** [comment]
@kevinsiji Can we fix it ASAP? I think this won't take much time to fix

**Comment by rakeshkonni** [comment]
Done

**Comment by rakeshkonni** [comment]
@kevinsiji or @Jayakrishnantu:  Can you please close this ticket?
