### ISSUE TITLE
Sound fields can have Studios too

### ISSUE THREAD

**Issue by rakeshkonni** [kevinsiji/m3db#117]
തൽസമയ ശബ്ദലേഖനം
ശബ്ദസന്നിവേശം (സൗണ്ട് എഡിറ്റിംഗ്) ​
ശബ്ദമിശ്രണം(ശബ്ദസങ്കലനം/സൗണ്ട് മിക്സിംഗ്/ഡിറ്റിഎസ് മിക്സിംഗ്)
ശബ്ദസംവിധാനം (ശബ്ദ രൂപകല്പന/സൗണ്ട് ഡിസൈൻ) 

എന്നീ ഫീൽഡുകളിൽ സ്റ്റുഡിയോയെയും ആർട്ടിസ്റ്റിനെയും ചേർക്കാൻ കഴിയണം

**Comment by kevinsiji** [comment]
Done
