### ISSUE TITLE
Image upload for posters

### ISSUE THREAD

**Issue by rakeshkonni** [kevinsiji/m3db#118]
ആർട്ടിസ്റ്റ് പ്രൊഫൈലിൽ പ്രൊഫൈൽ ഇമേജ് ചേർക്കുന്നപോലെ രണ്ടു ക്ലിക്കിൽ ഇമേജ് ചേർക്കാൻ പാകത്തിനാക്കുമോ, സിനിമ പോസ്റ്റേഴ്സും?

**Comment by kevinsiji** [comment]
Done
