### ISSUE TITLE
Film Search in Lyrics Page

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#121]
We use this feature very rarely but the Search option for Film Name is actually pointing to Artist Search. This option is needed when we search film names that are very small like Dum... 
![screen shot 2016-08-26 at 10 59 32 am](https://cloud.githubusercontent.com/assets/13643153/18015398/695093ba-6b7c-11e6-8dbe-b97f8c4a4fd1.png)

**Comment by kevinsiji** [comment]
FIXED
