### ISSUE TITLE
History Missing from Profile Page

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#15]
ലോഗിൻ ചെയ്ത ശേഷം പ്രൊഫൈൽ പേജിൽ ചെല്ലുമ്പോൾ എഡിറ്റിംഗ്, ക്രിയേറ്റഡ് ഹിസ്ററി കാണുന്നില്ല.

**Comment by kevinsiji** [comment]
Duplicate of Issue #6
