### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#17]
After login the Revisions pending are displayed.
![screen shot 2015-08-04 at 6 24 34 am](https://cloud.githubusercontent.com/assets/13643153/9061588/a19f926c-3a71-11e5-8935-f23a040e1e95.png)
But once you click on the heading, it takes to the 'Page Not Found' page.
![screen shot 2015-08-04 at 6 24 46 am](https://cloud.githubusercontent.com/assets/13643153/9061606/bac81e4e-3a71-11e5-85c0-cacd7e9330c9.png)

Page: http://www.m3db.com/content-summary

**Comment by kevinsiji** [comment]
Fixed
