### ISSUE TITLE
Artist Page - Unclassified Artists in Dropdown

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#19]
The very first option on the http://www.m3db.com/archive/artists/ page are unclassified artists. Those should really be classified under different alphabets.
![screen shot 2015-08-04 at 6 40 07 am](https://cloud.githubusercontent.com/assets/13643153/9061976/26df463c-3a74-11e5-8b72-58059761cf7e.png)

**Comment by kevinsiji** [comment]
There must be a "space" character in the beginning of those names.
