### ISSUE TITLE
Primary field

### ISSUE THREAD

**Issue by Achinthyaa** [kevinsiji/m3db#2]
An artist's profile page does not show his major contribution listed. For eg Sunny Joseph's page shows a single entry for his creative contribution where as he is primarily a cinematographer with exemplary contribution in the field.

**Comment by kevinsiji** [comment]
At the moment, the fields are listed in one order. We can change the order, but that same order will be used for all artists.

Sunny Joseph's cinematography credits are listed below the Creative contributions. See the screenshot.
![screencapture-www-m3db-com-artists-21137-1438673141390](https://cloud.githubusercontent.com/assets/3263439/9055418/998c7ebe-3aa8-11e5-9462-3e70fed27cc4.png)

**Comment by Achinthyaa** [comment]
But then for that we have to click on the field cinematography, right?

**Comment by Kiranz-m3db** [comment]
എനിക്ക് തോന്നുന്നത് വ്യത്യസ്ത മേഖലകളിൽ ശ്രദ്ധേയരായ വ്യക്തികളുടെ ഏറ്റവും ശ്രദ്ധേയമായ മേഖലയാണ് ആദ്യം കാണിക്കേണ്ടത് ? അത് എങ്ങനെ കാണിക്കും കെവീ ?

**Comment by kevinsiji** [comment]
Umechi, We have this option now, to list the things in tabbed style. Also if its necessary, we can go back to our old style (straight page without tabs.)

Kira, At present, no way to alter the order of fields for every page. Currently we can fix an order, so that the most famous fields come on top, and least famous fields go down. Eg: Director, Assi Director, etc. 
So if one person have been an Assi Direc for 50 films may have directed only 2 films, still his 2 films will show first, and 50 assi dir second.

**Comment by Achinthyaa** [comment]
Isnt the straight page style better?

**Comment by Kiranz-m3db** [comment]
I am also thinking why not..can we have a preview and if its not listing
good, probably we can go back to the new style and think of adding like
your suggestion Kevin ?

Best regards
Kiran

**Comment by kevinsiji** [comment]
Just to convert it will take a few hours. We have a lot of fields there to show.

**Comment by Kiranz-m3db** [comment]
cant we preview a sample one ?

Best regards
Kiran

**Comment by rakeshkonni** [comment]
Even if we go for straight page without tabs, the order will be pre-set, isn't it? 

Is there any way we can make it like the order can be customized by the data entry user?

**Comment by rakeshkonni** [comment]
Here's a related issue posted by Baiju
1. Open an artist page. For example: http://www.m3db.com/artists/825

It lists "ജഗതി ശ്രീകുമാർ എഴുതിയ ഗാനങ്ങൾ" I don't know if we can list in such way that it shows the prominent area of the artist --may be by the most number of entries.
1. Select another category named "സംവിധാനം ചെയ്ത സിനിമകൾ"
   It lists the movies directed by the artist. Sort the list based on year by clicking "വര്‍ഷം"--it takes you to the profile and the list changes from "ജഗതി ശ്രീകുമാർ അഭിനയിച്ച സിനിമകൾ"

to "ജഗതി ശ്രീകുമാർ എഴുതിയ ഗാനങ്ങൾ"

**Comment by kevinsiji** [comment]
@rakeshkonni  Thats a known bug in the software, not able to fix at the moment. Option available is to remove sorting in the profile page, and make sorting available only in the complete listing page.

**Comment by kevinsiji** [comment]
@Kiranz-m3db The Artists contributions are in a flat list now, as in our old site. I need a design for this format.

എല്ലാ പട്ടികകൾക്കും കൂടി ഒരു തലക്കെട്ടു് വേണം. കലാപ്രവർത്തനങ്ങൾ എന്നായാൽ ശരിയാവുമോ?

**Comment by Kiranz-m3db** [comment]
Why do we need a common title since its currently showing perfect..what
would be the pros and cons for this style Kevi ? More load for the server ?

If you need a title..I feel Kala praise than gal would be apt..

**Comment by Kiranz-m3db** [comment]
Kalapravarthangal would be apt as u suggested..previous one was auto
correction by phone

**Comment by kevinsiji** [comment]
There will not be any load difference. The one I made is modern user interface, where as flat list is old style.

I need to style this display, kumaretta, need a design for this section.

**Comment by rakeshkonni** [comment]
പ്രവർത്തനമേഖലകൾ എന്നായാലോ

Regards,
Rakesh

**Comment by Kiranz-m3db** [comment]
That's perfect :)

**Comment by kevinsiji** [comment]
I've styled the section headings myself. Let me know it looks good.

**Comment by Kiranz-m3db** [comment]
Yes it's looking cool Kevi.. the following is what you meant..right ?

[image: Inline image 1]

Best regards
Kiran
