### ISSUE TITLE
Lyrics Page - Alignment issue

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#22]
http://www.m3db.com/archive/lyrics/year/

![screen shot 2015-08-04 at 6 50 08 am](https://cloud.githubusercontent.com/assets/13643153/9062108/22de226e-3a75-11e5-8c13-e1e235e1ec2f.png)

Browser tried: Firefox

**Comment by kevinsiji** [comment]
Fixed
