### ISSUE TITLE
Direct uploading of Artist's profile images

### ISSUE THREAD

**Issue by swapnatakan** [kevinsiji/m3db#23]
Enable permission to upload profile images of artists directly from computer. Now its asking to upload somewhere else and give the URL,which doubles the job.

**Comment by kevinsiji** [comment]
Fixed. Thanks Kiranz

**Comment by swapnatakan** [comment]
thanks

On 6 August 2015 at 12:35, kevinsiji notifications@github.com wrote:

> Fixed. Thanks Kiranz
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kevinsiji/m3db/issues/23#issuecomment-128272172.

## 

Thanks»-(¯`v´¯)-»Regards...
☆☆♪സ്വപ്നാടകന്‍♬☆☆
+91 9995 288846

**Comment by swapnatakan** [comment]
What destination to choose?

Public local files served by the webserver.
Private local files served by Drupal.

On 6 August 2015 at 15:04, സ്വപ്നാടകന്‍ kpragesh@gmail.com wrote:

> thanks
> 
> On 6 August 2015 at 12:35, kevinsiji notifications@github.com wrote:
> 
> > Fixed. Thanks Kiranz
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kevinsiji/m3db/issues/23#issuecomment-128272172.
> 
> ## 
> 
> Thanks»-(¯`v´¯)-»Regards...
> ☆☆♪സ്വപ്നാടകന്‍♬☆☆
> +91 9995 288846

## 

Thanks»-(¯`v´¯)-»Regards...
☆☆♪സ്വപ്നാടകന്‍♬☆☆
+91 9995 288846

**Comment by kevinsiji** [comment]
Choose Public. 

Private is there for some historic reasons.

**Comment by kevinsiji** [comment]
While replying from email, pls remove the quoted text previous emails.
