### ISSUE TITLE
ആർട്ടിസ്റ്റുകളെ ഒരോ ഫീൽഡിൽ അസോസിയേറ്റ് ചെയ്യുമ്പോ ....

### ISSUE THREAD

**Issue by swapnatakan** [kevinsiji/m3db#34]
ആർട്ടിസ്റ്റുകളെ ഒരോ ഫീൽഡിൽ അസോസിയേറ്റ് ചെയ്യുമ്പോ നേരത്തേ, ഒരേ പേരിലുള്ളവരെ അവരവരുടെ ആര്ട്ടിസ്റ്സ് ഫീൽഡ് അടക്കം ലിസ്റ്റ് ചെയ്തിരുന്നു... ഇപ്പൊ കൊറേ പേരുകൾ മാത്രമേ ലിസ്റ്റ് ചെയ്യുന്നുള്ളൂ.. ആർട്ടിസ്റ്റ്സ് ഫീൽട്സ് ഇല്ല. തെറ്റായി അസോസിയേറ്റ് ചെയ്യാൻ വൻ സാധ്യതയാണത്. ഉദാഹരണത്തിന്,  അയാൾ ഞാനല്ല ഫിലിം എഡിറ്റ് എടുത്ത് കഥ ഫീൽഡിൽ രഞ്ജിത്ത് എന്ന് കൊടുത്താൽ അവിടെ രഞ്ജിത്ത് ഗോവിന്ദ്, സുധാ രഞ്ജിത്ത്, എം രഞ്ജിത്ത്, രഞ്ജിത്ത് അമ്പാടി, രഞ്ജിത്ത്, രഞ്ജിത്ത് ശങ്കർ, രഞ്ജിത്ത് ലാൽ, രഞ്ജിത്ത്, രഞ്ജിത്ത് ടച്ച്രിവർ, രഞ്ജിത്ത് എന്നിങ്ങനെയാണ് ലിസ്റ്റ് ചെയ്യുന്നത്..അതിൽ നിന്നും നമുക്ക് വേണ്ടയാൾ എങ്ങനാണെന്ന് എങ്ങനെ മനസ്സിലാവും? ആര്ട്ടിസ്റ്സ് ഫീല്ഡും അലിയാസും ഇല്ലാതെ അത് ബുദ്ധിമുട്ടാണ് .

**Comment by Neelakkurinji** [comment]
yes its difficult to find out who..

**Comment by kevinsiji** [comment]
ഡൺ
