### ISSUE TITLE
കഥാവസാനം എന്തു സംഭവിച്ചു? - Not Hidden

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#37]
![screen shot 2015-08-11 at 8 49 34 am](https://cloud.githubusercontent.com/assets/13643153/9202292/03890a82-4006-11e5-8c0b-1880ef1c7373.png)

It's visible. Not sure whether the hiding feature is removed.

**Comment by kevinsiji** [comment]
Fixed
