### ISSUE TITLE
Cant add new film page

### ISSUE THREAD

**Issue by Neelakkurinji** [kevinsiji/m3db#43]
cant add new film page, one msg is coming to try later ...
![error](https://cloud.githubusercontent.com/assets/13752642/9205277/431108d2-4072-11e5-85f8-2e7174cccd79.JPG)

**Comment by kevinsiji** [comment]
Fixed. Sorry for the delay, friends.

**Comment by rakeshkonni** [comment]
👍

Regards,
Rakesh
