### ISSUE TITLE
Cant add new lyrics

### ISSUE THREAD

**Issue by Neelakkurinji** [kevinsiji/m3db#46]
cant add new lyrics same issue ( while new film adding) occurs

**Comment by kevinsiji** [comment]
Is this problem there from the beginning onwards? or is it a new problem.

**Comment by Neelakkurinji** [comment]
dont know if this problem were there in the beginning, I just login in the
site yesterday after my vacvation
and started adding film, and lyrics.. cant do..

On Wed, Aug 12, 2015 at 10:14 AM, kevinsiji notifications@github.com
wrote:

> Is this problem there from the beginning onwards? or is it a new problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kevinsiji/m3db/issues/46#issuecomment-130182350.

## 

_( Ponnu ) http://www.m3db.com/user/3485_ http://www.m3db.com
Neelakkurinji http://www.m3db.com/neelakkurinji
www.malayalamsongslyrics.com
http://www.malayalamsongslyrics.com/lyrics_new/aboutus.php

**Comment by kevinsiji** [comment]
Fixed. Pls test.
