### ISSUE TITLE
Link going to the profile while selecting technicians

### ISSUE THREAD

**Issue by Neelakkurinji** [kevinsiji/m3db#47]
ലിറിക്സ് ചേർക്കുന്ന പേജിൽ ഗാനരചയിതാവ് , മ്യുസിക് ഡയറകടർ ഇവരെ ചേർക്കാൻ സെലക്റ്റ് ചെയുമ്പോ its going to their profile directly first, then have to select back again to come on the same page to save
Think this is good in one way to check the profile ( but at the same time waste also)

**Comment by kevinsiji** [comment]
Just don't click on the link, click anywhere else in the row.
