### ISSUE TITLE
Website encountered an unexpected error while creating new films with very basic details

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#55]
Serious issue since we are not able to add any new films with even very few details :( - Kindly add it as an urgent P0 case.

![image](https://cloud.githubusercontent.com/assets/13637422/9347465/7faa83de-4632-11e5-8088-870d49b9b491.png)

**Comment by kevinsiji** [comment]
I will try to complete fixing this today. Its a long process, each field have to be fixed. :(

**Comment by kevinsiji** [comment]
Duplicate of Issue #43
