### ISSUE TITLE
Labs are listed in Random Order

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#61]
![screen shot 2015-08-21 at 12 49 07 pm](https://cloud.githubusercontent.com/assets/13643153/9422685/26490bfc-4854-11e5-828f-76eaa78061ba.png)

Can We get this sorted in Alphabetical Order ?

**Comment by Jayakrishnantu** [comment]
@kevinsiji Can you please fix this one as an urgent one ? Hard time scrolling through the list to find out the labs :(

**Comment by kevinsiji** [comment]
sorry tta, for keeping you waiting for long.
Fixed.

**Comment by Jayakrishnantu** [comment]
(y)
