### ISSUE TITLE
** URGENT ** Few Issues - Artist Selection, Drop Down, Search 

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#69]
![screen shot 2015-08-24 at 7 45 41 am](https://cloud.githubusercontent.com/assets/13643153/9443170/793e9106-4a34-11e5-8b0b-9409081164c8.png)
The Artist name in the selection drop-down is a link, if we accidentally click on the link, we will be taken to the artists profile page, and when we come back, the whole data we entered will be lost.

![screen shot 2015-08-24 at 7 45 41 am](https://cloud.githubusercontent.com/assets/13643153/9443215/b29f66b4-4a34-11e5-8b1f-de44ee920b24.png)
Two issues here:
1. If we select a value for the artist field, Create a new artist option will become "Search Option", we won't be able to add a new artists from there.
2. I created a new artists from movie edit page (added details. uploaded profile pic & saved), but it was not saved. Gave me a reference error while saving the movie page.

**Comment by Jayakrishnantu** [comment]
![screen shot 2015-08-24 at 7 44 47 am](https://cloud.githubusercontent.com/assets/13643153/9443280/1603b354-4a35-11e5-8142-2e59a4d8592b.png)
Added a wrong screenshot for the 2nd issue

**Comment by Jayakrishnantu** [comment]
Please ignore that Artist creation issue, it was due to the language. :-)

**Comment by kevinsiji** [comment]
Fixed.
