### ISSUE TITLE
Graph shows different value other than actual value ?

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#70]
nadumuttathu koduthirikkunna graphil 1978-il cinemakal 249 anu. Ennal ivide (http://www.m3db.com/archive/year/1978) 134. Athentha?

![image](https://cloud.githubusercontent.com/assets/13637422/9447827/059d1d3a-4aa2-11e5-9928-f263400c28c3.png)

![image](https://cloud.githubusercontent.com/assets/13637422/9447839/16631bec-4aa2-11e5-87ba-dda048b826d9.png)

**Comment by kevinsiji** [comment]
Sorry, the graph included both language nodes :)

Fixed.
