### ISSUE TITLE
Request from Neeli to restore the old style of showing details of Data entry for films.

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#74]
Need to show the name of the person who adds the film on top like the old system
![image](https://cloud.githubusercontent.com/assets/13637422/9459033/d0e3479c-4afe-11e5-93c9-f62c4b9dc71d.png)

**Comment by rakeshkonni** [comment]
I would suggest to add the same under editing history itself:

ഇപ്പോഴുള്ളത്:
എഡിറ്റിങ് ചരിത്രം
13 edits by

It can be updated like below:

എഡിറ്റിങ് ചരിത്രം*ഈ പേജ് ഡേറ്റാബേസിൽ ചേർത്തത്:  *<User Name>

13 edits by

Regards,
Rakesh

**Comment by kevinsiji** [comment]
![screencapture-m3db-film-37058-2018-04-19-20_38_34](https://user-images.githubusercontent.com/3263439/39000550-ede96a4c-4411-11e8-97b5-aeb3275db5ce.png)
