### ISSUE TITLE
Titles Repeating in Artists Pages

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#80]
![screen shot 2015-08-25 at 1 22 27 pm](https://cloud.githubusercontent.com/assets/13643153/9478398/829c8be2-4b2c-11e5-808f-5666f7fd859f.png)

**Comment by rakeshkonni** [comment]
@kevinsiji. this could be a taken as high priority issue.

**Comment by kevinsiji** [comment]
Fixed.

**Comment by kevinsiji** [comment]
![screencapture-www-m3db-com-artists-21663-1455070161285](https://cloud.githubusercontent.com/assets/3263439/12936959/942f2bf4-cfc9-11e5-87fe-4bd6e2ba30d4.png)

**Comment by Jayakrishnantu** [comment]
(y)
