### ISSUE TITLE
Please merge these nodes - Awards

### ISSUE THREAD

**Issue by rakeshkonni** [kevinsiji/m3db#87]
Node 1 - http://www.m3db.com/award/27753
Node 2 - http://www.m3db.com/award/23443

Node 1 should be removed. Node 2 should be kept. Before removing, we should make sure that the reference is changed everywhere in the site. 

Or, please get the list of film nodes having reference to Node 1.

**Comment by rakeshkonni** [comment]
Another set:

Node 1 : http://www.m3db.com/awards/23296
Node 2: http://www.m3db.com/awards/24898

**Comment by kevinsiji** [comment]
> Node 1 - http://www.m3db.com/award/27753
> Node 2 - http://www.m3db.com/award/23443
> 
> Node 1 should be removed. Node 2 should be kept. Before removing, we should make sure that the >reference is changed everywhere in the site.
> 
> Or, please get the list of film nodes having reference to Node 1.

This is done. Once the references are changed to the correct one, we can delete the wrong one.

**Comment by kevinsiji** [comment]
> Another set:
> 
> Node 1 : http://www.m3db.com/awards/23296
> Node 2: http://www.m3db.com/awards/24898

This also fixed. Once the references are changed to the correct one, we can delete the wrong one.
