### ISSUE TITLE
Searching in manglish

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#9]
Is listing english nodes but can we redirect those entries to its malayalam nodes only ?
For eg: If we search G Venugopal it will list both but let it reach only the fully qualified malayalam entry ? I guess our earlier setting was like that..

![image](https://cloud.githubusercontent.com/assets/13637422/9056787/0d36408a-3a9e-11e5-9f7d-31b5dcb8ac35.png)
![image](https://cloud.githubusercontent.com/assets/13637422/9056795/1b5e1b38-3a9e-11e5-9cad-653227fd141a.png)

**Comment by kevinsiji** [comment]
What if the person who searched do not know to read Malayalam :)

**Comment by Kiranz-m3db** [comment]
i thank that should be the next phase..right ? Once we qualify all the
malayalam nodes, let us start creating profiles on english too ?

Best regards
Kiran

**Comment by kevinsiji** [comment]
No more relevant
