### ISSUE TITLE
Associate Editor - Not Listing

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#90]
This profile has so many films associated as "Asso Editor" but not listed.

![screen shot 2015-09-10 at 1 48 15 pm](https://cloud.githubusercontent.com/assets/13643153/9800601/b2b15aa4-57c2-11e5-999e-3ea6d4609cae.png)

**Comment by Jayakrishnantu** [comment]
http://www.m3db.com/artists/38080

**Comment by kevinsiji** [comment]
ഡൺ
