### ISSUE TITLE
Displaying Full list of Designs

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#91]
This is Artist Kitho's profile. http://www.m3db.com/artists/22276
![screen shot 2015-09-10 at 1 50 00 pm](https://cloud.githubusercontent.com/assets/13643153/9800638/f20c3bd8-57c2-11e5-8900-5bf38c66e987.png)

Clicking to see the full list of Designs will take to the Poster Design / Publicity section http://www.m3db.com/films-designs/22276

![screen shot 2015-09-10 at 1 51 48 pm](https://cloud.githubusercontent.com/assets/13643153/9800659/1abc7016-57c3-11e5-8ad1-e123504e5a64.png)

**Comment by kevinsiji** [comment]
ഡൺ
