### ISSUE TITLE
Issues while adding Dubbing Artist 

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#92]
1. No Fields are displaying against the Artists
   ![screen shot 2015-09-18 at 10 29 06 am](https://cloud.githubusercontent.com/assets/13643153/9966196/369caa48-5df0-11e5-8c18-35a4decbf4d7.png)
2. No Option to Add a new Artist & Search for an Artist
   ![screen shot 2015-09-18 at 10 28 52 am](https://cloud.githubusercontent.com/assets/13643153/9966202/43128f86-5df0-11e5-98b5-cf4dd301af38.png)

**Comment by rakeshkonni** [comment]
@kevinsiji, this could be a minor fix, right?

**Comment by kevinsiji** [comment]
ഡൺ
