### ISSUE TITLE
Suggestion: Search Artist for Data Entry

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#93]
![screen shot 2015-09-18 at 10 34 15 am](https://cloud.githubusercontent.com/assets/13643153/9966297/e83fa296-5df0-11e5-94b9-5268ad74ec5c.png)

When we do a search for example 'അരവിന്ദ' it list all entries containing 'അരവിന്ദ'.
Can you please introduce an option to select Starts with, Ends With and Contains while doing such search? It would be handy!

**Comment by kevinsiji** [comment]
Done
