### ISSUE TITLE
Limited form for film entry

### ISSUE THREAD

**Issue by kevinsiji** [kevinsiji/m3db#95]
**Fields required:**
1. Name
2. Director
3. Producer
4. Screenplay
5. Cast
6. Year
7. Tags

**Comment by rakeshkonni** [comment]
Story?

Regards,
Rakesh

**Comment by rakeshkonni** [comment]
കഥയെക്കാൾ തിരക്കഥ ചേർക്കുന്നതാണു ഉചിതം

Regards,
Rakesh

**Comment by kevinsiji** [comment]
Hello friends,

The minimal form for film entry is ready at http://www.m3db.com/node/add/film-mini

Pls test and report here.
