### ISSUE TITLE
Issue with New Film & New Songs Slot

### ISSUE THREAD

**Issue by rakeshkonni** [kevinsiji/m3db#96]
Please remove the crew details from the new film and new songs slots. I think posters with link should be enough.
![screenshot from 2015-09-25 15 06 35](https://cloud.githubusercontent.com/assets/13642831/10097532/505acb52-6397-11e5-986b-79740bbc14f8.png)

**Comment by rakeshkonni** [comment]
Or if we need to show the crew details, display Director in New Film and Music Director in New Songs

**Comment by kevinsiji** [comment]
Done
