### ISSUE TITLE
Tag year on the film title on lyric entry form

### ISSUE THREAD

**Issue by kevinsiji** [kevinsiji/m3db#97]

**Comment by kevinsiji** [comment]
ഡൺ

![film-field-ref-in-lyrics-2015-09-30 06 40 10](https://cloud.githubusercontent.com/assets/3263439/10182119/5990d37e-673e-11e5-8d91-1d66aa2e39e4.png)

**Comment by rakeshkonni** [comment]
ഇത് ലിറിക് എൻട്രി ഫോമിൽ മാത്രമാക്കേണ്ടാ. ഫിലിം സെർച്ച് ഫീൽഡുള്ള എല്ലാ
ഫോമിലും ആവാം ;)
