### ISSUE TITLE
Title Graphics field Not showing

### ISSUE THREAD

**Issue by Jayakrishnantu** [kevinsiji/m3db#98]
http://www.m3db.com/film/59140

![screen shot 2015-10-12 at 12 18 57 pm](https://cloud.githubusercontent.com/assets/13643153/10436507/b081ccc8-70db-11e5-8dc0-58cdecd9669e.png)

The filed is not showing up. Just the artist name is displayed.

**Comment by rakeshkonni** [comment]
This will be taken care in #81

**Comment by kevinsiji** [comment]
Fixed as per in #81
